// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompileEOP(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompileEOP'](arg1, arg2, arg3, arg4);
}

export function CompileSpaceWeather(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CompileSpaceWeather'](arg1, arg2, arg3, arg4);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadEOPCSV(arg1) {
  return window['go']['main']['App']['LoadEOPCSV'](arg1);
}

export function LoadSpaceWeatherCSV(arg1) {
  return window['go']['main']['App']['LoadSpaceWeatherCSV'](arg1);
}

export function LogMessage(arg1, arg2) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectSaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3);
}
