// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {eop} from '../models';
import {spaceweather} from '../models';

export function CompileEOP(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CompileSpaceWeather(arg1:boolean,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function LoadConfig():Promise<main.AppConfig>;

export function LoadEOPCSV(arg1:string):Promise<Array<eop.EOPRecord>>;

export function LoadSpaceWeatherCSV(arg1:string):Promise<Array<spaceweather.Record>>;

export function LogMessage(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function VerifyEOP(arg1:string,arg2:string):Promise<any>;

export function VerifySpaceWeather(arg1:string,arg2:string):Promise<any>;
